title: ASiS docs
description: Documentatie produs ASiSerp
theme: just-the-docs
search_enabled: true
search.rel_url: false
favicon_ico: "/assets/favicon.ico"
logo: "/assets/logo.png"

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://asw.ro
